### ISSUE TITLE
Proxy support needed

### ISSUE THREAD

**Issue by mimadiule** [FOLLGAD/zig-ai#1]
How to add proxy in the http connection?

**Comment by FOLLGAD** [comment]
Added support for this in https://github.com/FOLLGAD/zig-ai/commit/c9fcc3ccf7267b0881c42d64a48c82b09cdd7ec8. Just set the env variable `https_proxy` to your proxy URL like so:

```bash
export https_proxy="https://proxy.url.com:1234"
```
